### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by webWangjin** [zengwenfu/h5-creator#1]
大神 你好 按照步骤走没有打开
下面是报错内容

> h5-creator@1.0.0 start E:\Learn\h5 voluntry\h5-creator
> cross-env NODE_ENV=dev node server

express-session deprecated undefined resave option; provide resave option server.js:41:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option server.js:41:9
module.js:474
    throw err;
    ^

Error: Cannot find module './E:/Learn/h5 voluntry/h5-creator/server/routers/build.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Array.from (E:\Learn\h5 voluntry\h5-creator\server\routers\index.js:47:9)
    at Function.from (native)
    at module.exports (E:\Learn\h5 voluntry\h5-creator\server\routers\index.js:46:11)
    at Object.<anonymous> (E:\Learn\h5 voluntry\h5-creator\server.js:53:37)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! h5-creator@1.0.0 start: `cross-env NODE_ENV=dev node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the h5-creator@1.0.0 start script 'cross-env NODE_ENV=dev node server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the h5-creator package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=dev node server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs h5-creator
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls h5-creator
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Learn\h5 voluntry\h5-creator\npm-debug.log

**Comment by zengwenfu** [comment]
你好，不好意思，是我代码上的一个bug，在server/routers/index.js里面，使用了扫描目录的方式来引入路由，但是由于 windows 和 linux 系统的差异，这在 windows 中读取会失败，你可以自己看下这个文件的代码改为手动引入，或者等我晚上修复之后提交你再更新

**Comment by ruansongsong** [comment]
修好了吗

**Comment by ruansongsong** [comment]
改好了

**Comment by sunsmeil** [comment]
window  也是报这个错误

**Comment by zhaosanjin** [comment]
您好，你能说一下您如何修改的吗，我现在运行还是不行
